In [67]:
import pandas as pd

# Load the dataset
df = pd.read_csv("C:/Users/User/Documents/BeGep/archive/creditcard_2023.csv")

# Display the first few rows and some basic info
df_head = df.head()
df_info = df.info()
df_description = df.describe()
df_nulls = df.isnull().sum()

df_head, df_description, df_nulls


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568630 entries, 0 to 568629
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   id      568630 non-null  int64  
 1   V1      568630 non-null  float64
 2   V2      568630 non-null  float64
 3   V3      568630 non-null  float64
 4   V4      568630 non-null  float64
 5   V5      568630 non-null  float64
 6   V6      568630 non-null  float64
 7   V7      568630 non-null  float64
 8   V8      568630 non-null  float64
 9   V9      568630 non-null  float64
 10  V10     568630 non-null  float64
 11  V11     568630 non-null  float64
 12  V12     568630 non-null  float64
 13  V13     568630 non-null  float64
 14  V14     568630 non-null  float64
 15  V15     568630 non-null  float64
 16  V16     568630 non-null  float64
 17  V17     568630 non-null  float64
 18  V18     568630 non-null  float64
 19  V19     568630 non-null  float64
 20  V20     568630 non-null  float64
 21  V21     56

(   id        V1        V2        V3        V4        V5        V6        V7  \
 0   0 -0.260648 -0.469648  2.496266 -0.083724  0.129681  0.732898  0.519014   
 1   1  0.985100 -0.356045  0.558056 -0.429654  0.277140  0.428605  0.406466   
 2   2 -0.260272 -0.949385  1.728538 -0.457986  0.074062  1.419481  0.743511   
 3   3 -0.152152 -0.508959  1.746840 -1.090178  0.249486  1.143312  0.518269   
 4   4 -0.206820 -0.165280  1.527053 -0.448293  0.106125  0.530549  0.658849   
 
          V8        V9  ...       V21       V22       V23       V24       V25  \
 0 -0.130006  0.727159  ... -0.110552  0.217606 -0.134794  0.165959  0.126280   
 1 -0.133118  0.347452  ... -0.194936 -0.605761  0.079469 -0.577395  0.190090   
 2 -0.095576 -0.261297  ... -0.005020  0.702906  0.945045 -1.154666 -0.605564   
 3 -0.065130 -0.205698  ... -0.146927 -0.038212 -0.214048 -1.893131  1.003963   
 4 -0.212660  1.049921  ... -0.106984  0.729727 -0.161666  0.312561 -0.414116   
 
         V26       V27       V

In [68]:
# Könyvtárak
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Felesleges oszlopok eldobása (pl. idő, irreleváns jellemzők)
df = df.drop(columns=["Time", "V10", "V14", "V17"], errors="ignore")

# Célváltozó (Class) és bemenetek szétválasztása
X = df[["V1", "V2", "V3", "V4"]].copy()
X["Amount"] = df["Amount"]
y = df["Class"]

# Standardizálás + Zaj hozzáadása
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
np.random.seed(42)
X_noisy = X_scaled + np.random.normal(0, 2.0, X_scaled.shape)
X_final = np.round(X_noisy, 1)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.3, stratify=y, random_state=42)



In [69]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import joblib

#Oszlopok tisztítása (opcionális)
df = df.drop(columns=["Time", "V10", "V14", "V17"], errors="ignore")

#Cél és jellemzők szétválasztása
X = df[["V1", "V2", "V3", "V4"]].copy()
X["Amount"] = df["Amount"]
y = df["Class"]

#Normalizálás
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Train-test felosztás (80-20)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, stratify=y, random_state=42)

#Modell létrehozása és tanítása
logreg_model = LogisticRegression(max_iter=1000)
logreg_model.fit(X_train, y_train)

#Előrejelzés
y_pred = logreg_model.predict(X_test)

#Kiértékelés
print("🔍 Pontosság (Accuracy):", accuracy_score(y_test, y_pred))
print("\n📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n📈 Részletes jelentés:\n", classification_report(y_test, y_pred))

#Modell mentése apphoz
joblib.dump(logreg_model, "logreg_model.pkl")



🔍 Pontosság (Accuracy): 0.9339728821905281

📊 Confusion Matrix:
 [[53579  3284]
 [ 4225 52638]]

📈 Részletes jelentés:
               precision    recall  f1-score   support

           0       0.93      0.94      0.93     56863
           1       0.94      0.93      0.93     56863

    accuracy                           0.93    113726
   macro avg       0.93      0.93      0.93    113726
weighted avg       0.93      0.93      0.93    113726



['logreg_model.pkl']

In [77]:
#Könyvtárak importálása
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Adatok betöltése (feltételezzük, hogy df már létezik, pl. df = pd.read_csv("..."))
df = df.drop(columns=["Time", "V10", "V14", "V17"], errors="ignore")  # felesleges attribútumok eldobása

# Célváltozó és input szétválasztása
X = df[["V1", "V2", "V3", "V4"]]
X["Amount"] = df["Amount"]
y = df["Class"]

# Standardizálás
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Zaj hozzáadása és kerekítés
np.random.seed(42)
X_noisy = X_scaled + np.random.normal(0, 2.0, X_scaled.shape)  # erős zaj
X_rounded = np.round(X_noisy, 1)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_rounded, y, test_size=0.3, stratify=y, random_state=42)

# Random Forest modell létrehozása és tanítása
rf_model = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=42)
rf_model.fit(X_train, y_train)
rf_y_pred = rf_model.predict(X_test)

# Eredmények értékelése
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_cm = confusion_matrix(y_test, rf_y_pred)
rf_report = classification_report(y_test, rf_y_pred)

print(" Random Forest Eredmények:")
print(f" Pontosság (Accuracy): {rf_accuracy}")
print("\n Confusion Matrix:\n", rf_cm)
print("\nRészletes jelentés:\n", rf_report)
joblib.dump(rf_model, "random_forest_model.pkl")


C:\Users\User\AppData\Local\Temp\ipykernel_34736\717550639.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Amount"] = df["Amount"]


 Random Forest Eredmények:
 Pontosság (Accuracy): 0.6837252108869857

 Confusion Matrix:
 [[60132 25163]
 [28790 56504]]

Részletes jelentés:
               precision    recall  f1-score   support

           0       0.68      0.70      0.69     85295
           1       0.69      0.66      0.68     85294

    accuracy                           0.68    170589
   macro avg       0.68      0.68      0.68    170589
weighted avg       0.68      0.68      0.68    170589



['random_forest_model.pkl']

In [71]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Adat zajosítása
X_noisy = X_scaled + np.random.normal(0, 2.0, X_scaled.shape)
X_rounded = np.round(X_noisy, 1)

# Egyszerű, lebutított XGBoost modell beállítása
xgb_model = XGBClassifier(
    n_estimators=5,           # Minimális boosting lépések
    max_depth=1,              # Csak döntési rönkök (gyenge tanulók)
    learning_rate=0.05,       # Lassú tanulás, hogy ne tanuljon túl gyorsan
    subsample=0.3,            # Csak 30% adat minden iterációban
    colsample_bytree=0.3,     # Csak 30% változó minden iterációban
    use_label_encoder=False,
    eval_metric='logloss',
    verbosity=0,
    random_state=42
)

# Modell tanítása
xgb_model.fit(X_train, y_train)

# Előrejelzés teszt adaton
y_pred_xgb = xgb_model.predict(X_test)

# Kiértékelés
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
report_xgb = classification_report(y_test, y_pred_xgb)

# Eredmények megjelenítése
print("XGBoost Eredmények:")
print(f"Pontosság (Accuracy): {accuracy_xgb}")
print("\nConfusion Matrix:\n", conf_matrix_xgb)
print("\nRészletes jelentés:\n", report_xgb)


# Modell tanítása
xgb_model.fit(X_train, y_train)

# Előrejelzés teszt adaton
y_pred_xgb = xgb_model.predict(X_test)

# Kiértékelés
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
report_xgb = classification_report(y_test, y_pred_xgb)

# Eredmények megjelenítése
print("XGBoost Eredmények:")
print(f"Pontosság (Accuracy): {accuracy_xgb}")
print("\nConfusion Matrix:\n", conf_matrix_xgb)
print("\nRészletes jelentés:\n", report_xgb)
joblib.dump(xgb_model, "xgb_model.pkl")


XGBoost Eredmények:
Pontosság (Accuracy): 0.6395898914935898

Confusion Matrix:
 [[49965 35330]
 [26152 59142]]

Részletes jelentés:
               precision    recall  f1-score   support

           0       0.66      0.59      0.62     85295
           1       0.63      0.69      0.66     85294

    accuracy                           0.64    170589
   macro avg       0.64      0.64      0.64    170589
weighted avg       0.64      0.64      0.64    170589

XGBoost Eredmények:
Pontosság (Accuracy): 0.6395898914935898

Confusion Matrix:
 [[49965 35330]
 [26152 59142]]

Részletes jelentés:
               precision    recall  f1-score   support

           0       0.66      0.59      0.62     85295
           1       0.63      0.69      0.66     85294

    accuracy                           0.64    170589
   macro avg       0.64      0.64      0.64    170589
weighted avg       0.64      0.64      0.64    170589



['xgb_model.pkl']

In [72]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Adat zajosítása
X_noisy = X_scaled + np.random.normal(0, 2.0, X_scaled.shape)
X_rounded = np.round(X_noisy, 1)

# Gyenge (lebutított) MLP modell beállítása
mlp = MLPClassifier(
    hidden_layer_sizes=(10,),     # Egy rejtett réteg, mindössze 10 neuronnal
    activation='tanh',            # Egyszerűbb aktivációs függvény
    solver='sgd',                 # Sztochasztikus gradient descent (lassabb tanulás)
    learning_rate_init=0.01,      # Alacsony kezdő tanulási ráta
    max_iter=100,                 # Kevés iteráció
    random_state=42
)

# Tanítás
mlp.fit(X_train, y_train)

# Előrejelzés
y_pred_mlp = mlp.predict(X_test)

# Kiértékelés
acc_mlp = accuracy_score(y_test, y_pred_mlp)
cm_mlp = confusion_matrix(y_test, y_pred_mlp)
report_mlp = classification_report(y_test, y_pred_mlp)

# Eredmények megjelenítése
print("Neurális Háló (MLP) Eredmények:")
print(f"Pontosság (Accuracy): {acc_mlp}")
print("\nConfusion Matrix:\n", cm_mlp)
print("\nRészletes jelentés:\n", report_mlp)
joblib.dump(mlp, 'mlp_model.pkl')


Neurális Háló (MLP) Eredmények:
Pontosság (Accuracy): 0.7043361529758659

Confusion Matrix:
 [[61457 23838]
 [26599 58695]]

Részletes jelentés:
               precision    recall  f1-score   support

           0       0.70      0.72      0.71     85295
           1       0.71      0.69      0.70     85294

    accuracy                           0.70    170589
   macro avg       0.70      0.70      0.70    170589
weighted avg       0.70      0.70      0.70    170589



['mlp_model.pkl']

In [73]:
print(df.columns.tolist())


['id', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V11', 'V12', 'V13', 'V15', 'V16', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class']


In [74]:
import pandas as pd

# Modell összehasonlítás manuálisan megadott metrikák alapján
results_data = {
    "Modell": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost",
        "MLP (Neurális háló)"
    ],
    "Pontosság (Accuracy)": [
        0.9339728821905281,
        0.6837252108869857,
        0.6395898914935898,
        0.7043361529758659
    ],
    "F1-score (átlagolt)": [
        0.93,
        0.68,
        0.64,
        0.70
    ],
    "Precizitás (átlagolt)": [
        0.93,
        0.68,
        0.64,
        0.70
    ],
    "Recall (átlagolt)": [
        0.93,
        0.68,
        0.64,
        0.70
    ]
}

results_df = pd.DataFrame(results_data)
results_df.set_index("Modell", inplace=True)
results_df


Pontosság (Accuracy)  F1-score (átlagolt)  \
Modell                                                           
Logistic Regression              0.933973                 0.93   
Random Forest                    0.683725                 0.68   
XGBoost                          0.639590                 0.64   
MLP (Neurális háló)              0.704336                 0.70   

                     Precizitás (átlagolt)  Recall (átlagolt)  
Modell                                                         
Logistic Regression                   0.93               0.93  
Random Forest                         0.68               0.68  
XGBoost                               0.64               0.64  
MLP (Neurális háló)                   0.70               0.70

In [75]:
pip install kivy[base] kivy_examples --extra-index-url https://kivy.org/downloads/simple/


Looking in indexes: https://pypi.org/simple, https://kivy.org/downloads/simple/
Note: you may need to restart the kernel to use updated packages.
